# Generated by Django 2.1.1 on 2019-07-27 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0, null=True)),
                ('dish_type', models.CharField(max_length=200, null=True)),
                ('averageRating', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('res_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('score', models.FloatField(null=True)),
                ('number_of_visit', models.IntegerField(null=True)),
                ('Cuisine_Type', models.CharField(max_length=255, null=True)),
                ('Price_Range', models.IntegerField(null=True)),
                ('Phone', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Hours_Start', models.IntegerField(null=True)),
                ('Hours_End', models.IntegerField(null=True)),
                ('visit_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.Restaurant'),
        ),
    ]
