# Generated by Django 2.1.1 on 2019-07-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
