# Generated by Django 2.1.1 on 2019-07-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='Duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='Visit',
            field=models.IntegerField(null=True),
        ),
    ]
