# Generated by Django 2.1.1 on 2019-07-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190730_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='Duration',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='Price',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='Rating',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='Visit',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
